# Generated by Django 2.2.1 on 2019-05-22 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_of_questions', models.PositiveIntegerField(null=True)),
                ('query', models.CharField(max_length=250, null=True)),
                ('answer', models.CharField(max_length=250, null=True)),
                ('answers', models.TextField(null=True)),
                ('start_play', models.DateTimeField(null=True)),
                ('end_play', models.DateTimeField(null=True)),
                ('points', models.SmallIntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
