# Generated by Django 2.2.5 on 2019-09-19 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('set_of_questions', models.PositiveIntegerField(null=True)),
                ('query', models.CharField(max_length=250, null=True)),
                ('answer', models.CharField(max_length=250, null=True)),
                ('answers', models.TextField(null=True)),
                ('start_play', models.DateTimeField(null=True)),
                ('end_play', models.DateTimeField(null=True)),
                ('points', models.SmallIntegerField(null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
