# Generated by Django 2.0.6 on 2018-10-21 08:30

import django.db.models.deletion
from django.db import migrations, models

import validators.my_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('pesel', models.CharField(max_length=11, validators=[validators.my_validator.check_pesel])),
                ('status', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(null=True)),
                ('postal', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=10)),
                ('flat', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('workplace', models.CharField(max_length=100)),
                ('start_contract', models.DateField(null=True)),
                ('end_contract', models.DateField(blank=True, null=True)),
                ('overtime', models.IntegerField(choices=[(0, 'Clear contract'), (1, 'Weekly overtime'), (2, 'Saturday overtime')], default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHourlyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateField()),
                ('hourly_rate', models.FloatField(max_length=5)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee')),
            ],
        ),
    ]
