# Generated by Django 2.2.1 on 2019-05-22 10:16

from django.db import migrations, models
import django.db.models.deletion
import validators.my_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('forename', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('pesel', models.CharField(max_length=11, validators=[validators.my_validator.check_pesel])),
                ('status', models.BooleanField(default=False, verbose_name='Active')),
                ('leave', models.IntegerField(choices=[(0, 'Unpaid'), (1, 'Paid')], default=0)),
            ],
            options={
                'ordering': ['surname'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeHourlyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update', models.DateField(auto_now_add=True)),
                ('hourly_rate', models.FloatField(max_length=5)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('birthday', models.DateField(null=True)),
                ('postal', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=10)),
                ('flat', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('workplace', models.CharField(max_length=100)),
                ('start_contract', models.DateField(null=True)),
                ('end_contract', models.DateField(blank=True, null=True)),
                ('overtime', models.IntegerField(choices=[(0, 'Clear contract'), (1, 'Weekly overtime'), (2, 'Saturday overtime')], default=0)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
            options={
                'ordering': ['worker'],
            },
        ),
    ]
