# Generated by Django 2.0.9 on 2018-11-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20181114_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
