# Generated by Django 2.0.9 on 2018-12-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20181114_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='overtime',
            field=models.IntegerField(),
        ),
    ]
