# Generated by Django 2.0.9 on 2018-12-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_auto_20181223_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee'),
        ),
    ]
