# Generated by Django 2.0.9 on 2018-12-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_auto_20181225_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
