# Generated by Django 2.1.5 on 2019-02-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_auto_20181229_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehourlyrate',
            name='update',
            field=models.DateField(auto_now_add=True),
        ),
    ]
