# Generated by Django 2.2 on 2019-05-03 15:07

from django.db import migrations, models
import django.db.models.deletion
import validators.my_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cashregister', '0003_auto_20190502_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountancyDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('number', models.SmallIntegerField(verbose_name='Nr porządkowy dokumentu')),
                ('conveyance', models.CharField(max_length=25)),
                ('waybill', models.CharField(blank=True, max_length=100, verbose_name='Nr listu przewozowego')),
                ('date_of_shipment', models.DateField()),
                ('invoice', models.CharField(max_length=250, verbose_name='Numer faktury')),
                ('order', models.CharField(max_length=250, verbose_name='Zamówienie')),
                ('company', models.ForeignKey(limit_choices_to={'status__range': [1, 3]}, on_delete=django.db.models.deletion.DO_NOTHING, to='cashregister.Company')),
            ],
            options={
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=240)),
                ('nip', models.CharField(max_length=13)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal', models.CharField(blank=True, max_length=10, verbose_name='Postal code')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['customer'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200, unique=True, verbose_name='Nazwa Produktu')),
                ('unit', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'szt.'), (1, 'kpl.'), (2, 'tys.'), (3, 'ark.'), (4, 'ltr.'), (5, 'rola')], verbose_name='Jednostka masy')),
                ('netto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Wartość netto')),
                ('vat', models.DecimalField(choices=[(5, '5%'), (8, '8%'), (23, '23%'), (0, 'Zwolniony')], decimal_places=2, default=23, max_digits=4, verbose_name='Stawka podatku VAT')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AccountancyProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quanity', models.DecimalField(decimal_places=2, max_digits=9, validators=[validators.my_validator.positive_value], verbose_name='Ilość')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accountancy.AccountancyDocument')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accountancy.Products')),
            ],
            options={
                'ordering': ['product'],
            },
        ),
        migrations.AddField(
            model_name='accountancydocument',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'status__range': [1, 3]}, on_delete=django.db.models.deletion.DO_NOTHING, to='accountancy.Customer', verbose_name='Klient'),
        ),
    ]
