# Generated by Django 2.2 on 2019-05-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountancyproducts',
            name='netto_absolute',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='accountancyproducts',
            name='vat_absolute',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
