# Generated by Django 2.2 on 2019-04-14 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountancydocument',
            name='conveyance',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='accountancydocument',
            name='customer',
            field=models.ForeignKey(limit_choices_to={'status__range': [1, 3]}, on_delete=django.db.models.deletion.DO_NOTHING, to='accountancy.Customer', verbose_name='Klient'),
        ),
        migrations.AlterField(
            model_name='accountancydocument',
            name='date_of_shipment',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='accountancydocument',
            name='invoice',
            field=models.CharField(max_length=250, verbose_name='Numer faktury'),
        ),
        migrations.AlterField(
            model_name='accountancydocument',
            name='number',
            field=models.SmallIntegerField(verbose_name='Numer porządkowy dokumentu'),
        ),
        migrations.AlterField(
            model_name='accountancydocument',
            name='waybill',
            field=models.CharField(max_length=100, verbose_name='Numer listu przewozowego'),
        ),
    ]
