# Generated by Django 2.2 on 2019-05-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.IntegerField(choices=[(0, 'Closed'), (1, 'Operating'), (2, 'Suspended'), (3, 'Liquidation')], default=1),
        ),
    ]
