# Generated by Django 2.2 on 2019-05-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.DecimalField(choices=[(23, '23%'), (5, '5%'), (8, '8%'), (0, 'Zwolniony')], decimal_places=2, default=23, max_digits=4, verbose_name='Stawka podatku VAT'),
        ),
    ]
