# Generated by Django 2.2 on 2019-05-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0002_auto_20190505_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountancyproducts',
            old_name='netto_absolute',
            new_name='netto',
        ),
        migrations.RenameField(
            model_name='accountancyproducts',
            old_name='vat_absolute',
            new_name='vat',
        ),
    ]
