# Generated by Django 2.2 on 2019-04-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0002_auto_20190414_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountancydocument',
            name='waybill',
            field=models.CharField(blank=True, max_length=100, verbose_name='Numer listu przewozowego'),
        ),
    ]
