# Generated by Django 2.2 on 2019-04-14 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0003_auto_20190414_0818'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountancydocument',
            options={'ordering': ['-number']},
        ),
        migrations.AlterModelOptions(
            name='accountancyproducts',
            options={'ordering': ['product']},
        ),
    ]
