# Generated by Django 2.2 on 2019-04-14 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0004_auto_20190414_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountancyproducts',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='accountancy.AccountancyDocument'),
        ),
    ]
