# Generated by Django 2.2 on 2019-04-14 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0005_auto_20190414_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountancyproducts',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
