# Generated by Django 2.2 on 2019-04-14 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0007_auto_20190414_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
