# Generated by Django 2.2 on 2019-04-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0008_auto_20190414_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountancyproducts',
            name='quanity',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
