# Generated by Django 2.2 on 2019-04-14 22:42

from django.db import migrations, models
import validators.my_validator


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0009_auto_20190414_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountancyproducts',
            name='quanity',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[validators.my_validator.positive_value], verbose_name='Ilość'),
        ),
    ]
