# Generated by Django 2.2 on 2019-04-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountancy', '0010_auto_20190414_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='unit',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
