# Generated by Django 2.1.7 on 2019-02-17 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('symbol', models.CharField(blank=True, max_length=100, verbose_name='Symbol and document number')),
                ('contents', models.CharField(max_length=250)),
                ('income', models.FloatField(default=0.0)),
                ('expenditure', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=240)),
                ('nip', models.CharField(max_length=13)),
                ('street', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal', models.CharField(blank=True, max_length=10, verbose_name='Postal code')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('account', models.CharField(blank=True, max_length=34, verbose_name='Contrary account')),
                ('status', models.IntegerField(default=1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company'],
            },
        ),
        migrations.AddField(
            model_name='cashregister',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cashregister.Company'),
        ),
    ]
