# Generated by Django 2.2.1 on 2019-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
