# Generated by Django 2.1.7 on 2019-02-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='cashaccept',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashregister',
            name='cashpay',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
