# Generated by Django 2.1.7 on 2019-02-17 17:21

from django.db import migrations, models
import validators.my_validator


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='expenditure',
            field=models.FloatField(default=0.0, validators=[validators.my_validator.positive_value]),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='income',
            field=models.FloatField(default=0.0, validators=[validators.my_validator.positive_value]),
        ),
    ]
