# Generated by Django 2.1.7 on 2019-03-08 21:14

from django.db import migrations, models
import validators.my_validator


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0002_auto_20190305_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='contents',
            field=models.CharField(max_length=250, validators=[validators.my_validator.from_transfer]),
        ),
    ]
