# Generated by Django 2.1.7 on 2019-02-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0002_auto_20190217_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='symbol',
            field=models.CharField(max_length=100, verbose_name='Symbol and document number'),
        ),
    ]
