# Generated by Django 2.1.7 on 2019-03-08 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0003_auto_20190308_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='contents',
            field=models.CharField(max_length=250),
        ),
    ]
