# Generated by Django 2.1.7 on 2019-03-04 22:04

from django.db import migrations, models
import validators.my_validator


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0003_remove_cashregister_cashpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='contents',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='expenditure',
            field=models.FloatField(default=0.0, validators=[validators.my_validator.positive_value]),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='income',
            field=models.FloatField(default=0.0, validators=[validators.my_validator.positive_value]),
        ),
        migrations.AlterField(
            model_name='cashregister',
            name='symbol',
            field=models.CharField(max_length=100),
        ),
    ]
