# Generated by Django 2.1.7 on 2019-02-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0005_auto_20190220_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='symbol',
            field=models.CharField(max_length=100, verbose_name='Symbol'),
        ),
    ]
