# Generated by Django 2.1.7 on 2019-02-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0007_auto_20190221_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashregister',
            name='contents',
            field=models.CharField(max_length=250, verbose_name='Opis transakcji...'),
        ),
    ]
