# Generated by Django 2.1.7 on 2019-02-21 16:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cashregister', '0009_auto_20190221_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashregister',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='cashregister',
            name='date',
        ),
        migrations.AddField(
            model_name='cashregister',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
