# Generated by Django 2.0.6 on 2018-10-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkEvidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_work', models.DateTimeField(blank=True)),
                ('end_work', models.DateTimeField(blank=True)),
                ('jobhours', models.FloatField(blank=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee')),
            ],
            options={
                'ordering': ['worker', '-start_work'],
            },
        ),
    ]
