# Generated by Django 2.0.6 on 2018-10-21 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_date', models.DateField()),
                ('account_value', models.FloatField(default=50.0)),
                ('notice', models.TextField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee')),
            ],
            options={
                'ordering': ['-account_date', 'worker'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_flag', models.CharField(max_length=25)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employee.Employee')),
            ],
            options={
                'ordering': ['worker', '-leave_date'],
            },
        ),
    ]
