# Generated by Django 2.0.9 on 2018-12-21 20:45

from django.db import migrations, models
import validators.my_validator


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_accountpayment_employeeleave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workevidence',
            name='start_work',
            field=models.DateTimeField(blank=True,),
        ),
    ]
